### ISSUE TITLE
Definição dos Temas

### ISSUE THREAD

**Issue by joseevilasio** [joseevilasio/projetoquiz#10]
Definir os temas para as perguntas:

- 3 temas

Cada tema deve ter 10 perguntas com 4 respostas, 1 resposta correta. Deve ser armazenado em txt na seguinte estrutura: 

| Tema | Pergunta |   Resposta 1  | Resposta 2 | Resposta 3 | Resposta 4 | Resposta Certa |
| -------------  | --- | --- | --- | --- | --- | --- |
| Math | Quanto é 2+ 2? | 22 | 4 | 6 | 16 | 4 |

**Comment by joseevilasio** [comment]
@HugMagalhaes é possível utilizar o ChatGPT para criar as perguntar por tema.

**Comment by HugMagalhaes** [comment]
[bloco de nota para o projecto.txt](https://github.com/joseevilasio/projetoquiz/files/11826604/bloco.de.nota.para.o.projecto.txt)

**Comment by HugMagalhaes** [comment]
[bloco de nota para o projecto.txt](https://github.com/joseevilasio/projetoquiz/files/11826674/bloco.de.nota.para.o.projecto.txt)

**Comment by HugMagalhaes** [comment]
[Projecto de software.txt](https://github.com/joseevilasio/projetoquiz/files/11865900/Projecto.de.software.txt)

**Comment by joseevilasio** [comment]
Organizar os arquivos conforme reunião do dia 26-06.

separado por ficheiros com a seguinte formatação nometema-modo.txt

**Comment by HugMagalhaes** [comment]
[geografia cultura geral P normais.txt](https://github.com/joseevilasio/projetoquiz/files/11866470/geografia.cultura.geral.P.normais.txt)
[geografia cultura geral Pfaceis.txt](https://github.com/joseevilasio/projetoquiz/files/11866469/geografia.cultura.geral.Pfaceis.txt)
[georgrafia cultura geral P dificeis.txt](https://github.com/joseevilasio/projetoquiz/files/11866468/georgrafia.cultura.geral.P.dificeis.txt)

**Comment by HugMagalhaes** [comment]
[Matematica e Fisica Pfaceis .txt](https://github.com/joseevilasio/projetoquiz/files/11866787/Matematica.e.Fisica.Pfaceis.txt)
[Matematica e Fisica Pnormais.txt](https://github.com/joseevilasio/projetoquiz/files/11866786/Matematica.e.Fisica.Pnormais.txt)
[matematica fisica Pdificeis.txt](https://github.com/joseevilasio/projetoquiz/files/11866788/matematica.fisica.Pdificeis.txt)

**Comment by HugMagalhaes** [comment]
[quimica e Biologia PFaceis.txt](https://github.com/joseevilasio/projetoquiz/files/11879889/quimica.e.Biologia.PFaceis.txt)
[quimica e Biologia Pnormais.txt](https://github.com/joseevilasio/projetoquiz/files/11879890/quimica.e.Biologia.Pnormais.txt)

**Comment by HugMagalhaes** [comment]
[Quimica e Biologia Pdicieis.txt](https://github.com/joseevilasio/projetoquiz/files/11880023/Quimica.e.Biologia.Pdicieis.txt)

**Comment by HugMagalhaes** [comment]
[Quimica e Biologia Pdicieis.txt](https://github.com/joseevilasio/projetoquiz/files/11904876/Quimica.e.Biologia.Pdicieis.txt)
