### ISSUE TITLE
Sistema de login

### ISSUE THREAD

**Issue by joseevilasio** [joseevilasio/projetoquiz#13]
- Validação de email e palavra passe
- mascarar palavra passe digitada 
- retornar 0 para validação OK
- retornar 1 para validação falha
- sistema de bloqueio se errar 3 vezes
- linkar opção de recuperar senha #7

**Comment by HugMagalhaes** [comment]
Problemas no login,
O apagar no pass escrito não funciona

**Comment by HugMagalhaes** [comment]
carregar ou validar o password da variavél.
