### ISSUE TITLE
Sistema de Perguntas

### ISSUE THREAD

**Issue by Tijgadixa** [joseevilasio/projetoquiz#14]
Ler o tema;
Ler a dificuldade do tema; #6 
Rodar as perguntas;
Resposta imediata da solução;
Considerar a função tempo; #1
Receber a função de Pontos.

**Comment by joseevilasio** [comment]
Implementado, porém falta a funcionalidade de tempo e de comparar as respostas de forma correta. bug em transformar string vector em char.
