### ISSUE TITLE
Tela de Regras

### ISSUE THREAD

**Issue by Tijgadixa** [joseevilasio/projetoquiz#15]
Irá apresentar as regras do jogo

**Comment by HugMagalhaes** [comment]
[Regras do Jogo .txt](https://github.com/joseevilasio/projetoquiz/files/11879501/Regras.do.Jogo.txt)

**Comment by Tijgadixa** [comment]
Simplificar um pouco as regras:

Exemplo:
1. Sign-in/Login:
(...)
2. Jogo:
3 níveis dificuldade;
10 perguntas
certo dá 10 pontos
errado dá 0 pontos
no final mostrar pontos adquiridos nessa rodada mais pontos totais
tempo limite
3. Adicionais:
(...)

**Comment by HugMagalhaes** [comment]
[bloco regras do jogo.txt](https://github.com/joseevilasio/projetoquiz/files/11905041/bloco.regras.do.jogo.txt)
